### ISSUE TITLE
Problems when preparing requirements for ROS1

### ISSUE THREAD

**Issue by fmrico** [esteve/ros2_pepper#1]
When I run the scripts for ROS1 requirements I get the next error

> $ bash prepare_requirements_ros1.sh
> ...
> bash: /home/nao/Python-2.7.13/bin/python: No such file or directory
> 

I supposed that the error is produced by the last two lines of prepare_requirements_ros1.sh, so I changed to:

```
wget -O - -q https://bootstrap.pypa.io/get-pip.py | /home/nao/Python-${PYTHON2_VERSION}-pepper/bin/python && \
/home/nao/Python-${PYTHON2_VERSION-pepper}/bin/pip install empy catkin-pkg"
```
But I got new  errors : 

> + /home/nao/Python-2.7.13-pepper/bin/python
> Traceback (most recent call last):
>   File "<stdin>", line 28, in <module>
>   File "/home/nao/Python-2.7.13-pepper/lib/python2.7/tempfile.py", line 35, in <module>
>     from random import Random as _Random
>   File "/home/nao/Python-2.7.13-pepper/lib/python2.7/random.py", line 48, in <module>
>     from binascii import hexlify as _hexlify
> ImportError: libz.so.1: cannot open shared object file: No such file or directory

Setting LD_LIBRARY_PATH just before 

```
make install && \
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/nao/ctc/zlib/lib
wget -O - -q https://bootstrap.pypa.io/get-pip.py | /home/nao/Python-${PYTHON2_VERSION}-pepper/bin/python && \
/home/nao/Python-${PYTHON2_VERSION}-pepper/bin/pip install empy catkin-pkg"
```

produces more errors:

> ERROR:root:code for hash md5 was not found.
> Traceback (most recent call last):
>   File "/home/nao/Python-2.7.13-pepper/lib/python2.7/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/home/nao/Python-2.7.13-pepper/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type md5
> ERROR:root:code for hash sha1 was not found.
> Traceback (most recent call last):
>   File "/home/nao/Python-2.7.13-pepper/lib/python2.7/hashlib.py", line 147, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/home/nao/Python-2.7.13-pepper/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha1
> ERROR:root:code for hash sha224 was not found.

I get stuck :(

Any idea?

**Comment by fmrico** [comment]
Vale, solucionado. En breve haré un PR
